### ISSUE TITLE
Can you provide a simple example showing loading data from TF dataset or other in-memory objects

### ISSUE THREAD

**Issue by leocnj** [OverLordGoldDragon/dev_tg#11]
Thanks for creating this project. It will be very useful to allow TF users to have something like PyTorch Lighting.

I already have my codes that convert text files into TF Dataset and want to give DeepTrain a try. Will you please provide a simple example showing how to use Dataset in DataGenerator.

**Comment by OverLordGoldDragon** [comment]
It's best to post this issue at the [release repository](https://github.com/OverLordGoldDragon/deeptrain); I'll be able to help there. Strange you found this repo, though - mind telling me where you saw it?

**Comment by leocnj** [comment]
Okay. Just posted in your release repo. I learned deeptrain from today's Made with ML post on LinkedIn.
